### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by HooferDevelops** [discord-extensions/bubble-bar#2]
as per my last issue,
I can not get this theme to work.

I ask that you please help me, as you are entitled to as a theme developer.

if you will not help me, please delete all your other themes as you clearly do not care.

I cannot get this theme to work on my phone, I'm using aliucord on an Android. why won't it work? this is inexcusable.

**Comment by LuckFire** [comment]
listne here you lil shit, do it one more time and ill fold yo ass
