### ISSUE TITLE
Images overlap unread messages bar

### ISSUE THREAD

**Issue by lewisakura** [discord-extensions/bubble-bar#3]
![](https://discord.coffee/13AMwjF.png)
As you can see, the image is overlaying on top of the unread messages bar. I assume this is a z-indexing issue and is probably quite easily fixed with a `z-index: 999;` or the like. Funny styling go brr.

**Comment by LuckFire** [comment]
I'm certain that's an issue with Discord itself, as I've had it happen to me without the theme enabled.

(and after just checking, it seems like they fixed that as it's no longer happening on my end)
