### ISSUE TITLE
Move bar back down or accomodate bar in chat content

### ISSUE THREAD

**Issue by lewisakura** [discord-extensions/bubble-bar#4]
I'm aware this theme is meant to mimic Discord mobile, but this bar should probably be moved back down to underneath the chat box:
![](https://discord.coffee/6p4nJDG.png)
Main justification for this is that, with the way the bar is implemented right now, every time it appears it shifts the chat content up. It should either be moved back, or the chat content should always be shifted slightly up to accomodate the bar.

**Comment by LuckFire** [comment]
> every time it appears it shifts the chat content up.

this should no longer happen :+1:
