### ISSUE TITLE
The typing cursor is a little too close to the left than it probably should be.

### ISSUE THREAD

**Issue by SlippingGitty** [discord-extensions/bubble-bar#6]
### Issue
The typing cursor is a little too close to the left than it probably should be (?)

### Images
![image](https://user-images.githubusercontent.com/76500838/170797578-b00bb25b-990c-45b0-a349-acdd6698d3b1.png)
![image](https://user-images.githubusercontent.com/76500838/170797562-9aae30e9-bc84-4084-aac2-bceb007c30e8.png)

### Suggestion
I'm not entirely sure if this would be the best way of "fixing" it, but personally, I moved `.slateTextArea-27tjG0` a little bit like so:

```scss
.slateTextArea-27tjG0 {
    left: 5px;
}
```
![image](https://user-images.githubusercontent.com/76500838/170797329-ca0afdca-eb63-48dc-8173-5ce5b9e2e734.png)
![image](https://user-images.githubusercontent.com/76500838/170797502-f76d49d6-6501-44a2-9f08-8e9fc1c1f587.png)

Moving it 5px probably isn't the sweet spot for most, I just wanted to give an example.

**Comment by LuckFire** [comment]
yeah someone made a [pull request](https://github.com/Discord-Theme-Addons/bubble-bar/pull/5) that fixes it but i haven't accepted it yet since i plan on reworking this

**Comment by SlippingGitty** [comment]
thank you 👍
